# Generated by Django 3.2.18 on 2023-05-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('image', models.CharField(max_length=10000)),
                ('speaker', models.CharField(max_length=10000)),
                ('venue', models.CharField(max_length=10000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='YearGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=10000)),
                ('number', models.IntegerField(max_length=10000)),
                ('course', models.CharField(max_length=10000)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ministry')),
                ('year_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.yeargroup')),
            ],
        ),
    ]
